### ISSUE TITLE
Use in Rails 2

### ISSUE THREAD

**Issue by MZ2288** [brunofacca/active-record-query-trace#22]
Hi all,

I'm working with an enormous legacy app (Rails 2.3) with some pretty muddled spaghetti code in certain parts. Having the functionality provided by this gem would make some debugging and refactoring efforts significantly easier. Does anyone have suggestions as to how I might make this gem work in Rails 2? I realize it's using core features provided in Rails 3 and trying to reimplement them in a Rails 2 app would be insane. Any thoughts or suggestions would be well received. Thanks!

**Comment by brunofacca** [comment]
Sorry, @MZ2288, this project was no longer maintained for a while. I assume you updated your Rails version by now :smile:
