### ISSUE TITLE
Would you advise using ActiveRecord query trace in production?

### ISSUE THREAD

**Issue by fatuhoku** [brunofacca/active-record-query-trace#26]
Our app is pretty big, and whenever we see N+1 issues on production it's really isn't obvious where the problem could be fixed. Would you recommend using ActiveRecord query trace in production?

**Comment by ruckus** [comment]
Should be ok. worst case is just higher log content.

**Comment by fatuhoku** [comment]
Thanks! The guys at `bullet` recommended NOT to include their gem into production but maybe I'll go for this one.

**Comment by joshuapinter** [comment]
@fatuhoku I'm wondering the same thing. How was your experience with using it in Production? Did you experience any performance hits?

**Comment by brunofacca** [comment]
Hi @fatuhoku and @joshuapinter. Did you get to use the gem in production? If so, how did it go?

**Comment by joshuapinter** [comment]
No we didn’t but I’d still be interested in doing so and what other’s experiences are.

**Comment by brunofacca** [comment]
Please let me know if you ever try it in production. I'm implementing specs for the gem, that should make it even more reliable.

**Comment by patmaddox** [comment]
I haven't tried this, but it strikes me as a terrible idea. Calculating a backtrace is relatively expensive. Calculating a backtrace for every single SQL query in your production app is going to make it very, very slow.
