### ISSUE TITLE
Followed exact instructions for installation, error persists.

### ISSUE THREAD

**Issue by henrivrod** [brunofacca/active-record-query-trace#54]
in `block in materialize': Could not find active_record_query_trace-1.7 in any of the sources (Bundler::GemNotFound)

**Comment by brunofacca** [comment]
Hello. I'm sorry, but the information you provided does not say much about the cause of the issue. It seems like an issue with your Bundler environment. I would try the following steps:
1. Run `bundle install`
2. Start your application with `bundle exec <whatever command you were trying to run>`
3. If that doesn't work, it may be a problem with your Gemfile.lock file. 
    * If your project is on a Git repository, try checking out Gemfile.lock from master and running `bundle install` again. 
    * If you're the only one working in the project and it's not yet deployed to production, try deleting Gemfile.lock and running `bundle install` again.
