### ISSUE TITLE
Alternative mode: add a comment with file:number to the SQL query

### ISSUE THREAD

**Issue by Nowaker** [brunofacca/active-record-query-trace#58]
Rather than printing traces to stdout, it'd be great to annotate queries with the stacktrace or the first non-framework frame:
```sql
SELECT 1; -- app/controllers/blah.rb:87
```
This way we're not spamming stdout with irrelevant data. Instead, we're annotating queries, and only when a query is slow and lands in the slowlog, the stacktrace is saved. It's a more storage-efficient and cost-efficient way of doing what the plugin currently does! :)

**Comment by brunofacca** [comment]
Hello @Nowaker. Thank you for the suggestion. It would be a nice addition to the gem. Unfortunately, I don't have the bandwidth to implement it. PRs are always welcome :slightly_smiling_face:.

**Comment by Nowaker** [comment]
I've found https://github.com/basecamp/marginalia - this is doing exactly what I was looking for! :)

**Comment by brunofacca** [comment]
Cool, it seems like a nice gem.
