### ISSUE TITLE
Log in Rail's test env

### ISSUE THREAD

**Issue by kleinjm** [brunofacca/active-record-query-trace#59]
I apologize if I'm missing this in the documentation but would it be possible to log to the test log in in the rails test env?

**Comment by brunofacca** [comment]
Hi @kleinjm. The gem does not implement a feature that does that, but with a bit of Rails hacking, you should be able to do it. I'd like to help but I just don't have the bandwidth at this moment. Sorry and good luck.

**Comment by kleinjm** [comment]
Understood, thanks for the quick reply!
