### ISSUE TITLE
Use Outside of Rails

### ISSUE THREAD

**Issue by ddoherty03** [brunofacca/active-record-query-trace#9]
I would like to use this gem in a non-rails app that uses AR.  Not sure how to get this hooked into the app though.

Could you add some commentary to the README to address this?

Thanks.

**Comment by ruckus** [comment]
Hmm, yeah I'm not clear on how to do that either. 

A quick look indicate that the only references to `Rails` is in the `clean_trace` method, so maybe a quick hack would be:

```ruby
def clean_trace(trace)
  if !defined?(Rails)
    return trace
  else

  case ActiveRecordQueryTrace.level
  when :full
    trace
  when :rails
    Rails.respond_to?(:backtrace_cleaner) ? Rails.backtrace_cleaner.clean(trace) : trace
  when :app
    Rails.backtrace_cleaner.add_silencer { |line| not line =~ /^app/ }
    Rails.backtrace_cleaner.clean(trace)
  end
end
```

**Comment by ddoherty03** [comment]
OK, thanks.  But the reference to Rails in the code is something I didn't think about.  I guess I will run into that when I get the gem hooked into my app.

That's my real question.  My app (byr) creates its own logger as an ActiveSupport::Logger, thus.

```ruby
file = make_log_file
Byr.logger = ActiveRecord::Base.logger = ActiveSupport::Logger.new(file, 'weekly')
ActiveRecordQueryTrace.enabled = true

# CONFIG: log formatting
Byr.logger.formatter = proc do |severity, datetime, _progname, msg|
  "#{severity}:#{datetime.strftime('%F(%^a)@%I:%M:%S.%3N')}:\n  #{msg.wrap(78, 4)}\n"
end
```
I get no query tracing with this.  I've tried setting the enabled flag in different places, but it still seems to just log AR queries as usual, no tracing.  The README says to set it in the config file, which is rails-specific.

Any idea how I can get it working?  I'm looking forward to being able to track down where in my source a series of seemingly identical queries are being called from.

Thanks for the gem.

**Comment by palkan** [comment]
Using without Rails now should be possible via setting the custom backtrace cleaner (see https://github.com/brunofacca/active-record-query-trace/pull/49):

```ruby
ActiveRecordQueryTrace.level = :custom
ActiveRecordQueryTrace.backtrace_cleaner = ->(trace) {
  trace.reject { |line| line =~ /\b(active_record_query_trace|active_support|active_record|another_gem)\b/ }
}
```

**Comment by ddoherty03** [comment]
@brunofacca, thanks for the head-up.
